//! A small textual LLVM IR builder.
//!
//! Local variables live in `alloca` slots and are promoted to registers by
//! LLVM's mem2reg pass, which keeps loop emission simple. Reductions carry the
//! `reassoc` flag so LLVM may vectorise them; that is the one place where Mint
//! deliberately departs from strict IEEE evaluation order (see
//! docs/architecture.md). `--strict-fp` turns every fast-math flag off.

use std::collections::{BTreeSet, HashMap};

pub fn fconst(v: f64) -> String {
    format!("0x{:016X}", v.to_bits())
}

#[derive(Default)]
pub struct Module {
    pub decls: BTreeSet<String>,
    pub globals: Vec<String>,
    pub funcs: Vec<String>,
    strings: HashMap<String, String>,
}

impl Module {
    pub fn string(&mut self, s: &str) -> String {
        if let Some(g) = self.strings.get(s) {
            return g.clone();
        }
        let name = format!("@.str.{}", self.strings.len());
        let mut bytes = String::new();
        for b in s.bytes().chain(std::iter::once(0u8)) {
            if b.is_ascii_alphanumeric() || b == b' ' || (b.is_ascii_punctuation() && b != b'"' && b != b'\\') {
                bytes.push(b as char);
            } else {
                bytes += &format!("\\{:02X}", b);
            }
        }
        self.globals.push(format!("{name} = private unnamed_addr constant [{} x i8] c\"{bytes}\"", s.len() + 1));
        self.strings.insert(s.to_string(), name.clone());
        name
    }

    pub fn declare(&mut self, line: &str) {
        self.decls.insert(line.to_string());
    }

    pub fn finish(self) -> String {
        let mut out = String::from("; generated by mintc\n\n");
        for d in &self.decls {
            out += d;
            out.push('\n');
        }
        out.push('\n');
        for g in &self.globals {
            out += g;
            out.push('\n');
        }
        out.push('\n');
        for f in &self.funcs {
            out += f;
            out.push('\n');
        }
        out
    }
}

pub struct Fb {
    lines: Vec<String>,
    allocas: Vec<String>,
    n: usize,
    hoist: Option<(usize, Vec<String>)>,
    pub frees: Vec<String>,
    /// fast-math flags for ordinary arithmetic and for reductions
    pub flags: &'static str,
    pub rflags: &'static str,
    pub strict: bool,
}

impl Fb {
    pub fn new(strict_fp: bool) -> Self {
        Fb {
            lines: vec![],
            allocas: vec![],
            n: 0,
            hoist: None,
            frees: vec![],
            flags: if strict_fp { "" } else { "contract " },
            rflags: if strict_fp { "" } else { "reassoc contract " },
            strict: strict_fp,
        }
    }

    pub fn reg(&mut self) -> String {
        self.n += 1;
        format!("%r{}", self.n)
    }

    pub fn label(&mut self, base: &str) -> String {
        self.n += 1;
        format!("{base}{}", self.n)
    }

    pub fn emit(&mut self, s: impl AsRef<str>) {
        self.lines.push(format!("  {}", s.as_ref()));
    }

    pub fn start_block(&mut self, l: &str) {
        self.lines.push(format!("{l}:"));
    }

    pub fn br(&mut self, l: &str) {
        self.emit(format!("br label %{l}"));
    }

    pub fn alloca(&mut self, ty: &str) -> String {
        let r = self.reg();
        self.allocas.push(format!("  {r} = alloca {ty}"));
        r
    }

    /// Emits instructions at the start of the current top-level statement
    /// instead of here, so buffers used inside loops are allocated once.
    pub fn begin_hoist(&mut self) {
        self.hoist = Some((self.lines.len(), vec![]));
    }

    pub fn end_hoist(&mut self) {
        if let Some((at, h)) = self.hoist.take() {
            self.lines.splice(at..at, h);
        }
    }

    pub fn hoisted<T>(&mut self, f: impl FnOnce(&mut Fb) -> T) -> T {
        if self.hoist.is_none() {
            return f(self);
        }
        let saved = std::mem::take(&mut self.lines);
        let r = f(self);
        let produced = std::mem::replace(&mut self.lines, saved);
        self.hoist.as_mut().unwrap().1.extend(produced);
        r
    }

    // ---- arithmetic helpers

    pub fn fop(&mut self, op: &str, a: &str, b: &str) -> String {
        let r = self.reg();
        let flags = self.flags;
        self.emit(format!("{r} = {op} {flags}double {a}, {b}"));
        r
    }
    pub fn fadd(&mut self, a: &str, b: &str) -> String {
        self.fop("fadd", a, b)
    }
    pub fn fsub(&mut self, a: &str, b: &str) -> String {
        self.fop("fsub", a, b)
    }
    pub fn fmul(&mut self, a: &str, b: &str) -> String {
        self.fop("fmul", a, b)
    }
    pub fn fdiv(&mut self, a: &str, b: &str) -> String {
        self.fop("fdiv", a, b)
    }
    pub fn fneg(&mut self, a: &str) -> String {
        let r = self.reg();
        self.emit(format!("{r} = fneg double {a}"));
        r
    }
    pub fn iop(&mut self, op: &str, a: &str, b: &str) -> String {
        let r = self.reg();
        self.emit(format!("{r} = {op} i64 {a}, {b}"));
        r
    }
    pub fn imul(&mut self, a: &str, b: &str) -> String {
        self.iop("mul nsw", a, b)
    }
    pub fn iadd(&mut self, a: &str, b: &str) -> String {
        self.iop("add nsw", a, b)
    }
    pub fn sitofp(&mut self, a: &str) -> String {
        let r = self.reg();
        self.emit(format!("{r} = sitofp i64 {a} to double"));
        r
    }
    pub fn intrinsic1(&mut self, m: &mut Module, name: &str, a: &str) -> String {
        m.declare(&format!("declare double @{name}(double)"));
        let r = self.reg();
        self.emit(format!("{r} = call double @{name}(double {a})"));
        r
    }
    pub fn intrinsic2(&mut self, m: &mut Module, name: &str, a: &str, b: &str) -> String {
        m.declare(&format!("declare double @{name}(double, double)"));
        let r = self.reg();
        self.emit(format!("{r} = call double @{name}(double {a}, double {b})"));
        r
    }

    // ---- memory helpers

    pub fn gep(&mut self, p: &str, idx: &str) -> String {
        let r = self.reg();
        self.emit(format!("{r} = getelementptr inbounds double, ptr {p}, i64 {idx}"));
        r
    }
    pub fn load(&mut self, p: &str, idx: &str) -> String {
        let a = self.gep(p, idx);
        let r = self.reg();
        self.emit(format!("{r} = load double, ptr {a}"));
        r
    }
    pub fn store(&mut self, v: &str, p: &str, idx: &str) {
        let a = self.gep(p, idx);
        self.emit(format!("store double {v}, ptr {a}"));
    }
    /// p[idx] += v
    pub fn add_to(&mut self, p: &str, idx: &str, v: &str) {
        let a = self.gep(p, idx);
        let old = self.reg();
        self.emit(format!("{old} = load double, ptr {a}"));
        let s = self.fadd(&old, v);
        self.emit(format!("store double {s}, ptr {a}"));
    }
    pub fn load_ptr(&mut self, g: &str) -> String {
        let r = self.reg();
        self.emit(format!("{r} = load ptr, ptr {g}"));
        r
    }
    pub fn load_i64(&mut self, g: &str) -> String {
        let r = self.reg();
        self.emit(format!("{r} = load i64, ptr {g}"));
        r
    }
    pub fn load_f64(&mut self, g: &str) -> String {
        let r = self.reg();
        self.emit(format!("{r} = load double, ptr {g}"));
        r
    }
    pub fn memcpy(&mut self, m: &mut Module, dst: &str, src: &str, n_doubles: &str) {
        m.declare("declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)");
        let bytes = self.imul(n_doubles, "8");
        self.emit(format!("call void @llvm.memcpy.p0.p0.i64(ptr {dst}, ptr {src}, i64 {bytes}, i1 false)"));
    }
    pub fn memzero(&mut self, m: &mut Module, dst: &str, n_doubles: &str) {
        m.declare("declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)");
        let bytes = self.imul(n_doubles, "8");
        self.emit(format!("call void @llvm.memset.p0.i64(ptr {dst}, i8 0, i64 {bytes}, i1 false)"));
    }

    // ---- accumulators (alloca-backed, promoted to phis by mem2reg)

    pub fn acc_new(&mut self, init: &str) -> String {
        let a = self.alloca("double");
        self.emit(format!("store double {init}, ptr {a}"));
        a
    }
    /// Reduction update: carries `reassoc` so the loop can be vectorised.
    pub fn acc_add(&mut self, acc: &str, v: &str) {
        let old = self.reg();
        self.emit(format!("{old} = load double, ptr {acc}"));
        let r = self.reg();
        let fl = self.rflags;
        self.emit(format!("{r} = fadd {fl}double {old}, {v}"));
        self.emit(format!("store double {r}, ptr {acc}"));
    }
    pub fn acc_get(&mut self, acc: &str) -> String {
        self.load_f64(acc)
    }

    // ---- control flow

    pub fn finish(self, header: &str, epilogue: &[String]) -> String {
        let mut out = format!("{header} {{\nentry:\n");
        for a in &self.allocas {
            out += a;
            out.push('\n');
        }
        for l in &self.lines {
            out += l;
            out.push('\n');
        }
        for l in epilogue {
            out += "  ";
            out += l;
            out.push('\n');
        }
        out += "}\n";
        out
    }
}

pub trait HasFb {
    fn fb(&mut self) -> &mut Fb;
}

/// for i in lo..hi { body(i) }
pub fn for_range<C: HasFb>(cx: &mut C, lo: &str, hi: &str, body: impl FnOnce(&mut C, &str)) {
    let f = cx.fb();
    let iv = f.alloca("i64");
    f.emit(format!("store i64 {lo}, ptr {iv}"));
    let hdr = f.label("loop");
    let bb = f.label("body");
    let exit = f.label("done");
    f.br(&hdr);
    f.start_block(&hdr);
    let i = f.reg();
    f.emit(format!("{i} = load i64, ptr {iv}"));
    let c = f.reg();
    f.emit(format!("{c} = icmp slt i64 {i}, {hi}"));
    f.emit(format!("br i1 {c}, label %{bb}, label %{exit}"));
    f.start_block(&bb);
    body(cx, &i);
    let f = cx.fb();
    let i2 = f.reg();
    f.emit(format!("{i2} = add nsw i64 {i}, 1"));
    f.emit(format!("store i64 {i2}, ptr {iv}"));
    f.br(&hdr);
    f.start_block(&exit);
}

/// For i in 0..n: store(i, sum_k M[i*c + k] * v[k]).
/// Rows are processed four at a time so each load of v feeds four FMAs;
/// LLVM vectorises the four independent reductions.
pub fn rows_dot_blocked<C: HasFb>(cx: &mut C, m: &str, v: &str, c: &str, n: &str, store: &dyn Fn(&mut C, &str, &str)) {
    let nb = cx.fb().iop("sdiv", n, "4");
    for_range(cx, "0", &nb, |cx, b| {
        let f = cx.fb();
        let i0 = f.imul(b, "4");
        let mut ids = Vec::new();
        let mut rows = Vec::new();
        for l in 0..4 {
            let i = f.iadd(&i0, &l.to_string());
            rows.push(f.imul(&i, c));
            ids.push(i);
        }
        let accs: Vec<String> = (0..4).map(|_| f.acc_new(&fconst(0.0))).collect();
        for_range(cx, "0", c, |cx, k| {
            let f = cx.fb();
            let x = f.load(v, k);
            for l in 0..4 {
                let idx = f.iadd(&rows[l], k);
                let a = f.load(m, &idx);
                let t = f.fmul(&a, &x);
                f.acc_add(&accs[l], &t);
            }
        });
        for l in 0..4 {
            let s = cx.fb().acc_get(&accs[l]);
            store(cx, &ids[l], &s);
        }
    });
    let done = cx.fb().imul(&nb, "4");
    for_range(cx, &done, n, |cx, i| {
        let f = cx.fb();
        let row = f.imul(i, c);
        let acc = f.acc_new(&fconst(0.0));
        for_range(cx, "0", c, |cx, k| {
            let f = cx.fb();
            let idx = f.iadd(&row, k);
            let a = f.load(m, &idx);
            let x = f.load(v, k);
            let t = f.fmul(&a, &x);
            f.acc_add(&acc, &t);
        });
        let s = cx.fb().acc_get(&acc);
        store(cx, i, &s);
    });
}

/// For k in 0..c: g[k] += sum_i coef(i) * M[i*c + k], four rows per pass over g.
pub fn rows_axpy_blocked<C: HasFb>(cx: &mut C, m: &str, c: &str, n: &str, coef: &dyn Fn(&mut C, &str) -> String, g: &str) {
    let nb = cx.fb().iop("sdiv", n, "4");
    for_range(cx, "0", &nb, |cx, b| {
        let i0 = cx.fb().imul(b, "4");
        let mut rows = Vec::new();
        let mut cs = Vec::new();
        for l in 0..4 {
            let i = cx.fb().iadd(&i0, &l.to_string());
            cs.push(coef(cx, &i));
            rows.push(cx.fb().imul(&i, c));
        }
        for_range(cx, "0", c, |cx, k| {
            let f = cx.fb();
            let mut sum: Option<String> = None;
            for l in 0..4 {
                let idx = f.iadd(&rows[l], k);
                let a = f.load(m, &idx);
                let t = f.fmul(&cs[l], &a);
                sum = Some(match sum {
                    None => t,
                    Some(s) => f.fadd(&s, &t),
                });
            }
            f.add_to(g, k, &sum.unwrap());
        });
    });
    let done = cx.fb().imul(&nb, "4");
    for_range(cx, &done, n, |cx, i| {
        let a = coef(cx, i);
        let row = cx.fb().imul(i, c);
        for_range(cx, "0", c, |cx, k| {
            let f = cx.fb();
            let idx = f.iadd(&row, k);
            let x = f.load(m, &idx);
            let t = f.fmul(&a, &x);
            f.add_to(g, k, &t);
        });
    });
}
