#!/usr/bin/env python3
"""Writes src/dynpois.rs from baselines/dynpois_par.rs, so that the
hand-tuned kernel is the same code, not a retyped copy. Only these changes
are made (each asserted to apply):

- the Martin runtime's thread team (mint_par_groups / mint_par_threads) is
  replaced by this crate's own (src/team.rs: par_groups / par_threads);
- glibc's vector exp (which needs nightly Rust's simd_ffi and libmvec) is
  dropped: only Martin's table exp remains (DYNPOIS_EXP=table, the default
  and the fastest in bench/same_sampler), plus the fused/back variants;
- the file's main(), the runtime FFI and common.rs are left out.

usage: python make_kernel.py   (from this directory or anywhere)
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "..", "baselines", "dynpois_par.rs")
lines = open(SRC).read().split("\n")


def span(first, last):
    """Lines first..last (1-based, inclusive), checked by their content."""
    return "\n".join(lines[first - 1:last])


def find(prefix, start=0):
    for i in range(start, len(lines)):
        if lines[i].startswith(prefix):
            return i + 1
    raise SystemExit(f"not found: {prefix!r}")


a = find("const SD_BETA")
b = find("extern \"C\" {") - 1          # constants up to the runtime FFI
c = find("/// Thread count forced by the self-test")
d = find("fn main()") - 1                # everything up to main
body = span(a, b) + "\n" + span(c, d)

subs = [
    ("mint_par_threads()", "par_threads()"),
    ("mint_par_groups(kernel", "par_groups(kernel"),
    ("_ZGVdN4v_exp(", "exp4("),
    ("        Ok(\"glibc\") => EXP_GLIBC,\n", ""),
    ("DYNPOIS_EXP must be table, fused, back or glibc", "DYNPOIS_EXP must be table, fused or back"),
]
for old, new in subs:
    assert old in body, old
    body = body.replace(old, new)

header = '''//! GENERATED by make_kernel.py from baselines/dynpois_par.rs: the
//! hand-tuned log density and gradient (AVX2/FMA, Martin's table exp, blocks
//! of eight series split across the chain's threads). Changes from the
//! source: the thread team is this crate's (team.rs) instead of the Martin
//! runtime's, and glibc's vector exp is not available (every `exp4` call in
//! an EXP_GLIBC branch is dead code; the mode cannot be selected).
#![allow(dead_code, clippy::all)]
use std::cell::RefCell;
use std::ffi::c_void;
use std::sync::atomic::{AtomicI64, Ordering};
use std::sync::OnceLock;

use crate::team::{par_groups, par_threads};
pub use std::arch::x86_64::*;

#[inline(always)]
pub unsafe fn hsum(v: __m256d) -> f64 {
    let lo = _mm256_castpd256_pd128(v);
    let hi = _mm256_extractf128_pd(v, 1);
    let s = _mm_add_pd(lo, hi);
    let h = _mm_unpackhi_pd(s, s);
    _mm_cvtsd_f64(_mm_add_sd(s, h))
}

'''
body = body.replace("static FORCE_NT", "pub static FORCE_NT")
body = body.replace("\nstruct Data {", "\npub struct Data {")
body = body.replace("    fn new(g: usize, t: usize, y: Vec<f64>) -> Data", "    pub fn new(g: usize, t: usize, y: Vec<f64>) -> Data")
body = body.replace("    fn dim(&self) -> usize", "    pub fn dim(&self) -> usize")
body = body.replace("    g: usize,\n    t: usize,", "    pub g: usize,\n    pub t: usize,")
body = body.replace("unsafe fn logp_impl(", "pub unsafe fn logp_impl(")
body = body.replace("fn logp_reference(", "pub fn logp_reference(")
body = body.replace("\nfn selftest(", "\npub fn selftest(")
# the Martin-runtime callbacks are not used here
body = body.replace("extern \"C\" fn logp(theta: *const f64, grad: *mut f64) -> f64 {\n    unsafe { logp_impl(DATA.get().unwrap(), theta, grad) }\n}\n", "")
body = body.replace("extern \"C\" fn constrain(unc: *const f64, out: *mut f64) {\n    let d = DATA.get().unwrap().dim();\n    unsafe { std::ptr::copy_nonoverlapping(unc, out, d) };\n}\n", "")
out = os.path.join(HERE, "src", "dynpois.rs")
open(out, "w").write(header + body + "\n")
print(f"wrote {out} ({len((header + body).splitlines())} lines)")
